module.exports = {
  SET_ERRORS: "SET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",

  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  LOGOUT: "LOGOUT",

  USER_PROFILE: "USER_PROFILE",
  TRACKS_INDEX: "TRACKS_INDEX",
  CREATE_TRACK: "CREATE_TRACK",
  UPDATE_TRACK: "UPDATE_TRACK",

  CREATE_COMMENT: "CREATE_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT"

};
