module.exports = {
  RECEIVE_ALL_TRACKS: "RECEIVE_ALL_TRACKS",
  RECEIVE_SINGLE_TRACK: "RECEIVE_SINGLE_TRACK",
  REMOVE_TRACK: "REMOVE_TRACK",
  
  SET_CURRENT_TRACK: "SET_CURRENT_TRACK",
  PAUSE_CURRENT_TRACK: "PAUSE_CURRENT_TRACK",
  PLAY_NEXT_TRACK: "PLAY_NEXT_TRACK",
  PLAY_PREVIOUS_TRACK: "PLAY_PREVIOUS_TRACK"
};
